name: Publish

on:
  # Triggers the workflow on release events
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest
    
    env:
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      LIBRARY_VERSION: ${{ github.event.release.tag_name }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Publish to CocoaPods
        run: pod trunk push ${{ github.event.repository.name }}.podspec
