name: Publish

on:
  # Triggers the workflow on release events
  pull_request:
    types:
        - opened
        - synchronize
        - edited
        - reopened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest
    
    env:
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      LIBRARY_VERSION: "2.0.2"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Print the path to pod
        run: which pod
      
      - name: Update CocoaPods
        run: gem update cocoapods
      
      - name: Print the CocoaPods version
        run: pod --version
      
      - name: Publish to CocoaPods
        run: pod lib lint
