name: Test

# Controls when the action will run. 
on:
  pull_request:
  
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  package: SwiftyTable-Package

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_on_ios:
    runs-on: macos-latest
    
    env:
      IOS_SIMULATOR: "iPhone 13"
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build for iOS
        run: xcodebuild build -scheme ${{ env.package }} -destination "name=${{ env.IOS_SIMULATOR }}"
        
      - name: Run tests on iOS
        run: xcodebuild test -scheme ${{ env.package }} -destination "name=${{ env.IOS_SIMULATOR }}"
        
  test_on_tvos:
    runs-on: macos-latest
    
    env:
      TVOS_SIMULATOR: "Apple TV"
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build for tvOS
        run: xcodebuild build -scheme ${{ env.package }} -destination "name=${{ env.TVOS_SIMULATOR }}"
        
      - name: Run tests on tvOS
        run: xcodebuild test -scheme ${{ env.package }} -destination "name=${{ env.TVOS_SIMULATOR }}"
